#include <stdbool.h>
#include <Python.h>
#include "tensor.h"
#include "operators.h"

PyObject *reshape(PyObject *self, PyObject *const *args, size_t nargsf, PyObject *kwnames);
// PyObject *permute(PyObject *self, PyObject *args);
PyObject *transpose(PyObject *self, PyObject *const *args, size_t nargsf, PyObject *kwnames);
// PyObject *squeeze(PyObject *self, PyObject *args);
// PyObject *unsqueeze(PyObject *self, PyObject *args);
// PyObject *flatten(PyObject *self, PyObject *args);
// PyObject *cat(PyObject *self, PyObject *args);
// PyObject *stack(PyObject *self, PyObject *args);
// PyObject *split(PyObject *self, PyObject *args);
// PyObject *chunk(PyObject *self, PyObject *args);
// PyObject *gather(PyObject *self, PyObject *args);
// PyObject *slice(PyObject *self, PyObject *args);
// PyObject *random(PyObject *self, PyObject *args);
Tensor *_sin(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_cos(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_tan(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_asin(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_acos(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_atan(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_sinh(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_cosh(PyObject *self, PyObject *const *args, size_t nargsf);
// PyObject *sec(PyObject *self, PyObject *args);
// PyObject *csc(PyObject *self, PyObject *args);
// PyObject *cot(PyObject *self, PyObject *args);
// PyObject *sech(PyObject *self, PyObject *args);
// PyObject *csch(PyObject *self, PyObject *args);
// PyObject *coth(PyObject *self, PyObject *args);
Tensor *_tanh(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_asinh(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_acosh(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_atanh(PyObject *self, PyObject *const *args, size_t nargsf);
// PyObject *sigmoid(PyObject *self, PyObject *args);
// PyObject *relu(PyObject *self, PyObject *args);
// PyObject *leaky_relu(PyObject *self, PyObject *args);
// PyObject *gelu(PyObject *self, PyObject *args);
// PyObject *softmax(PyObject *self, PyObject *args);
// PyObject *log_softmax(PyObject *self, PyObject *args);
// PyObject *mean(PyObject *self, PyObject *args);
Tensor *_sum(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_max(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_min(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_argmax_wrapper(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_argmin_wrapper(PyObject *self, PyObject *const *args, size_t nargsf);
// PyObject *topk(PyObject *self, PyObject *args);
Tensor *_exp(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_log(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_log10(PyObject *self, PyObject *const *args, size_t nargsf);
Tensor *_sqrt(PyObject *self, PyObject *const *args, size_t nargsf);
// PyObject *_abs(PyObject *self, PyObject *args);
// PyObject *_pow(PyObject *self, PyObject *args);

// PyObject *reshape_backward(PyObject *self, PyObject *args);
// PyObject *permute_backward(PyObject *self, PyObject *args);
// PyObject *transpose_backward(PyObject *self, PyObject *args);
// PyObject *squeeze_backward(PyObject *self, PyObject *args);
// PyObject *unsqueeze_backward(PyObject *self, PyObject *args);
// PyObject *flatten_backward(PyObject *self, PyObject *args);
// PyObject *cat_backward(PyObject *self, PyObject *args);
// PyObject *stack_backward(PyObject *self, PyObject *args);
// PyObject *split_backward(PyObject *self, PyObject *args);
// PyObject *chunk_backward(PyObject *self, PyObject *args);
// PyObject *gather_backward(PyObject *self, PyObject *args);
// PyObject *slice_backward(PyObject *self, PyObject *args);
// PyObject *random_backward(PyObject *self, PyObject *args);
// PyObject *sin_backward(PyObject *self, PyObject *args);
// PyObject *cos_backward(PyObject *self, PyObject *args);
// PyObject *tan_backward(PyObject *self, PyObject *args);
// PyObject *asin_backward(PyObject *self, PyObject *args);
// PyObject *acos_backward(PyObject *self, PyObject *args);
// PyObject *atan_backward(PyObject *self, PyObject *args);
// PyObject *sinh_backward(PyObject *self, PyObject *args);
// PyObject *cosh_backward(PyObject *self, PyObject *args);
// PyObject *sec_backward(PyObject *self, PyObject *args);
// PyObject *csc_backward(PyObject *self, PyObject *args);
// PyObject *cot_backward(PyObject *self, PyObject *args);
// PyObject *sech_backward(PyObject *self, PyObject *args);
// PyObject *csch_backward(PyObject *self, PyObject *args);
// PyObject *coth_backward(PyObject *self, PyObject *args);
// PyObject *tanh_backward(PyObject *self, PyObject *args);
// PyObject *asinh_backward(PyObject *self, PyObject *args);
// PyObject *acosh_backward(PyObject *self, PyObject *args);
// PyObject *atanh_backward(PyObject *self, PyObject *args);
// PyObject *sigmoid_backward(PyObject *self, PyObject *args);
// PyObject *relu_backward(PyObject *self, PyObject *args);
// PyObject *leaky_relu_backward(PyObject *self, PyObject *args);
// PyObject *gelu_backward(PyObject *self, PyObject *args);
// PyObject *softmax_backward(PyObject *self, PyObject *args);
// PyObject *log_softmax_backward(PyObject *self, PyObject *args);
// PyObject *mean_backward(PyObject *self, PyObject *args);
// PyObject *sum_backward(PyObject *self, PyObject *args);
// PyObject *max_backward(PyObject *self, PyObject *args);
// PyObject *min_backward(PyObject *self, PyObject *args);
// PyObject *argmax_backward(PyObject *self, PyObject *args);
// PyObject *argmin_backward(PyObject *self, PyObject *args);
// PyObject *topk_backward(PyObject *self, PyObject *args);
// PyObject *exp_backward(PyObject *self, PyObject *args);
// PyObject *log_backward(PyObject *self, PyObject *args);
// PyObject *sqrt_backward(PyObject *self, PyObject *args);
// PyObject *abs_backward(PyObject *self, PyObject *args);
// PyObject *pow_backward(PyObject *self, PyObject *args);
