from typing import Any

def abs(*args, **kwargs) -> Any: ...
def arccos(*args, **kwargs) -> Any: ...
def arccosh(*args, **kwargs) -> Any: ...
def arcsin(*args, **kwargs) -> Any: ...
def arcsinh(*args, **kwargs) -> Any: ...
def arctan(*args, **kwargs) -> Any: ...
def arctanh(*args, **kwargs) -> Any: ...
def argmax(*args, **kwargs) -> Any: ...
def argmin(*args, **kwargs) -> Any: ...
def cos(*args, **kwargs) -> Any: ...
def cosh(*args, **kwargs) -> Any: ...
def exp(*args, **kwargs) -> Any: ...
def log(*args, **kwargs) -> Any: ...
def log10(*args, **kwargs) -> Any: ...
def max(*args, **kwargs) -> Any: ...
def mean(*args, **kwargs) -> Any: ...
def min(*args, **kwargs) -> Any: ...
def power(*args, **kwargs) -> Any: ...
def reshape(*args, **kwargs) -> Any: ...
def sin(*args, **kwargs) -> Any: ...
def sinh(*args, **kwargs) -> Any: ...
def sqrt(*args, **kwargs) -> Any: ...
def sum(*args, **kwargs) -> Any: ...
def tan(*args, **kwargs) -> Any: ...
def tanh(*args, **kwargs) -> Any: ...
def transpose(*args, **kwargs) -> Any: ...
